services:
  postgres:
    image: postgres:16-alpine
    container_name: wex_postgres
    restart: always
    environment:
      POSTGRES_USER: wex_user
      POSTGRES_PASSWORD: wex_password
      POSTGRES_DB: wex_db
    ports:
      - '5432:5432'
    volumes:
      - wex_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U wex_user -d wex_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wex-purchase-challenge-net

  api:
    build:
      context: .
      dockerfile: DockerFile
    container_name: wex_api
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://wex_user:wex_password@postgres:5432/wex_db?schema=public
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - wex-purchase-challenge-net

volumes:
  wex_pgdata:
    driver: local

networks:
  wex-purchase-challenge-net:
    driver: bridge
